name: FRONT-WORKFLOW
on:
  push:
    branches: [ "main" ]
jobs:
  front-job:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # 오류 발생 시 스크립트 중단
            set -e
            
            # SSH 접속 후 작업 디렉토리로 이동
            echo "SSH 접속"
            cd front

            # 환경 설정 파일 생성
            echo "환경 설정 파일 생성"
            echo -e "REACT_APP_REST_SERVER=${{ secrets.REST_SERVER }}" >> .env
            echo -e "REACT_APP_GOOGLE_ID=${{ secrets.GOOGLE_ID }}" >> .env
            echo -e "REACT_APP_GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
            echo -e "REACT_APP_KAKAO_ID=${{ secrets.KAKAO_ID }}" >> .env
            echo -e "REACT_APP_KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env

            git_output=$(sudo git pull origin main 2>&1)
            
            docker compose up -d --build
